/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 23, 2016 at 5:12:31 PM Argentina Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MFSwipeActionUtilities : NSObject
+(unsigned long long)swipeActionForActionKey:(id)arg1 ;
+(id)actionKeyForSwipeAction:(unsigned long long)arg1 ;
+(id)defaultColorForSwipeAction:(unsigned long long)arg1 ;
+(id)defaultIconForSwipeAction:(unsigned long long)arg1 alternate:(BOOL)arg2 ;
+(BOOL)isActionDestructive:(unsigned long long)arg1 ;
@end

